/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.comunidad;

import java.util.LinkedList;
import java.util.List;
import multichain.command.CommandElt;
import multichain.command.MultichainException;
import multichain.object.StreamKey;
import multichain.object.StreamKeyItem;

/**
 *
 * @author AndresF
 */
public class Antecedentes extends javax.swing.JFrame {

    /**
     * Creates new form Antecedentes
     */
    public Antecedentes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Antecedentes");

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        jButton1.setText("Consultar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Delito");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("Identificacion");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(17, 17, 17)
                        .addComponent(jRadioButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CAntecedentes CA = new CAntecedentes();
        List<StreamKeyItem> keys;
        String op = jList2.getSelectedValue();
        String mostrar = "";
        try{
           if (op.equals("Leve")){
               keys = (List<StreamKeyItem>) Main.commandManager.invoke(CommandElt.LISTSTREAMKEYITEMS,"antecedentes","1");
               for (StreamKeyItem key : keys) {
                   List<String> ids = key.getKeys();
                   String id = ids.get(0);
                   List<StreamKeyItem>   nombres = (List<StreamKeyItem>) Main.commandManager.invoke(CommandElt.LISTSTREAMKEYITEMS,"individuos",id);
                   for (StreamKeyItem nombre : nombres) {
                       mostrar += nombre.getData() + "\n";
                   }
                   mostrar += key.getData() +"\n";
               }
               CA.jTextArea1.setText(mostrar);
               CA.setVisible(true);
           }
           else if (op.equals("Comun")){
                keys = (List<StreamKeyItem>) Main.commandManager.invoke(CommandElt.LISTSTREAMKEYITEMS,"antecedentes","2");
                for (StreamKeyItem key : keys) {
                   List<String> ids = key.getKeys();
                   String id = ids.get(0);
                   List<StreamKeyItem>   nombres = (List<StreamKeyItem>) Main.commandManager.invoke(CommandElt.LISTSTREAMKEYITEMS,"individuos",id);
                   for (StreamKeyItem nombre : nombres) {
                       mostrar += nombre.getData() + "\n";
                   }
                   mostrar += key.getData() +"\n";
               }
               CA.jTextArea1.setText(mostrar);
               CA.setVisible(true);
           }
           else if (op.equals("Grave")){
                keys = (List<StreamKeyItem>) Main.commandManager.invoke(CommandElt.LISTSTREAMKEYITEMS,"antecedentes","3");
                for (StreamKeyItem key : keys) {
                   List<String> ids = key.getKeys();
                   String id = ids.get(0);
                   List<StreamKeyItem>   nombres = (List<StreamKeyItem>) Main.commandManager.invoke(CommandElt.LISTSTREAMKEYITEMS,"individuos",id);
                   for (StreamKeyItem nombre : nombres) {
                       mostrar += nombre.getData() + "\n";
                   }
                   mostrar += key.getData() +"\n";
               }
               CA.jTextArea1.setText(mostrar);
               CA.setVisible(true);
           }
           else {
               keys = (List<StreamKeyItem>) Main.commandManager.invoke(CommandElt.LISTSTREAMKEYITEMS,"antecedentes",op);
                for (StreamKeyItem key : keys) {
                   List<String> ids = key.getKeys();
                   String id = ids.get(0);
                   List<StreamKeyItem>   nombres = (List<StreamKeyItem>) Main.commandManager.invoke(CommandElt.LISTSTREAMKEYITEMS,"individuos",id);
                   mostrar += nombres.get(0).getData() + "\n";
                   mostrar += key.getData() +"\n";
                   }
               }
               CA.jTextArea1.setText(mostrar);
               CA.setVisible(true);
           }
 
        catch (MultichainException e){
             e.printStackTrace();
         }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
            jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Leve", "Comun", "Grave"};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
         List<StreamKey> keys;
        LinkedList<String> keys2 = new LinkedList<>();
        try{
            Main.commandManager.invoke(CommandElt.SUBSCRIBE, "individuos");
            keys = (List<StreamKey>) Main.commandManager.invoke(CommandElt.LISTSTREAMKEYS,"individuos");
            for (StreamKey key : keys) {
                keys2.add(key.getKey());
            }
        }
        catch (MultichainException e){
            e.printStackTrace();
        }
        Object[] objectAarray = keys2.toArray();
        int length = objectAarray.length;;
        String [] arraystrings = new String[length];
        for(int i =0; i < length; i++) {
            arraystrings[i] = (String) objectAarray[i];
        }
        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = arraystrings;
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
    }//GEN-LAST:event_jRadioButton4ActionPerformed


    public static void executeA2() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Antecedentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Antecedentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Antecedentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Antecedentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Antecedentes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
