/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.comunidad;
import multichain.command.CommandManager;
import multichain.object.StreamKeyItem;
import multichain.command.MultichainException;
import multichain.command.CommandElt;

/**
 *
 * @author AndresF
 */
public class Form extends javax.swing.JFrame {

    /**
     * Creates new form form
     */
    public Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        rIndividuo = new javax.swing.JButton();
        rAntecedente = new javax.swing.JButton();
        cAntecedentes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bienvenido");

        rIndividuo.setText("Registrar Individuo");
        rIndividuo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rIndividuoActionPerformed(evt);
            }
        });

        rAntecedente.setText("Registrar Antecedente");
        rAntecedente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rAntecedenteActionPerformed(evt);
            }
        });

        cAntecedentes.setText("Consultar Antecedentes");
        cAntecedentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cAntecedentesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(165, 165, 165)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(126, 126, 126)
                                .addComponent(rIndividuo)))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(rAntecedente)
                        .addComponent(cAntecedentes)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(80, 80, 80)
                .addComponent(rIndividuo)
                .addGap(70, 70, 70)
                .addComponent(rAntecedente)
                .addGap(81, 81, 81)
                .addComponent(cAntecedentes)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rIndividuoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rIndividuoActionPerformed
        Individuo I = new Individuo();
        I.setVisible(true);
    }//GEN-LAST:event_rIndividuoActionPerformed

    private void rAntecedenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rAntecedenteActionPerformed
        Antecedente A = new Antecedente();
        A.setVisible(true);
    }//GEN-LAST:event_rAntecedenteActionPerformed

    private void cAntecedentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cAntecedentesActionPerformed
        Antecedentes As = new Antecedentes();
        As.setVisible(true);
    }//GEN-LAST:event_cAntecedentesActionPerformed


    public static void execute() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cAntecedentes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton rAntecedente;
    private javax.swing.JButton rIndividuo;
    // End of variables declaration//GEN-END:variables
}
